#! /bin/bash
#
# turns nicely formatted JS objects into markdown tables
#
sed -e 's/^\(    \)\([a-zA-Z]*\)\(: \)/| \2	|/' -e 's/\(|\s*\)\([a-zA-Z0-9()]*\)\(,\)/| \2	|/' -e 's/\(^  \)\([a-zA-Z]*\)\(:.*\)/| *\2*	| 	|/' | grep '	' | sed -e 's;\(\s*\)\(/\*\)\(.*\);\3;' -e 's;\*/\s*$;	|;' | column -s '	' -t
